### ISSUE TITLE
animation code please

### ISSUE THREAD

**Issue by zhangsuyou** [mattnedrich/GradientDescentExample#10]
dear matt:
i am a beginner in machine learning.Thanks for your code,make me learn a lot.
i'm interested in the dynamic graph you made,and try to recurrence it.But when i learn and use "matplotlib.animation",i met some problms.i think,if you can give me your animation code,it will be of great help to me.
thank you very much!:)

**Comment by mattnedrich** [comment]
I rendered / saved individual frames (plots as the state advanced) and turned them into a GIF
