### ISSUE TITLE
Changing Learning rate to 0.0005 will get invalid value encountered in double_scalars warning

### ISSUE THREAD

**Issue by astrung** [mattnedrich/GradientDescentExample#2]
I change Learning rate to 0.0005, and i get the following warning message:
gradient_descent_example.py:23: RuntimeWarning: invalid value encountered in double_scalar
  new_m = m_current - (learningRate \* m_gradient)
.
And this is result:
    "After 10000 iterations b = nan, m = nan, error = nan"
How to fix it???

**Comment by mattnedrich** [comment]
My guess is that this happens due to division by zero - http://stackoverflow.com/questions/27784528/numpy-division-with-runtimewarning-invalid-value-encountered-in-double-scalars.
