### ISSUE TITLE
Visualisatioin

### ISSUE THREAD

**Issue by mohebbim** [mattnedrich/GradientDescentExample#3]
Hi matt , thanks for your great example it's really helped me  a lot , I was wondering if you have the codes for the visualisation (plots) you have used to demonstrate gradient descent , as that would help me have a deeper understanding of how it works. 
many thanks

**Comment by mattnedrich** [comment]
I can work on adding the visualization code. In general, I plotted the points after each iteration and saved the plots as images, then turned them into an animated gif.

**Comment by mohebbim** [comment]
Hi Matt, 

Thanks again for your example , it demonstrates many important concepts in Machine Learning  and it has helped me out a lot as someone who has just started learning about the topic of Machine learning.
I have since implemented my own code which uses a procedural approach for implementing the gradient descent, however I am still not a 100% certain that my visualisations for the surface plot and the contour is very accurate as I used a bit of code from a chinese website to implement the following for the  Z axis. z = 2 \* x \* x + 5 \* y \* y - 4 \* x \* y , and I am not sure why they have used this formula.

Overall I think I have made some progress both in the programming aspect of Machine learning as well as implementing a simple linear regression program thanks to your example.

I have attached my codes in a text file and I would really appreciate it if you could take the time to have a quick look at what I have done and give me your comments , feedbacks or ideas.

Kind regards.

Ali.

[Linear-Regression_GD.txt](https://github.com/mattnedrich/GradientDescentExample/files/392406/Linear-Regression_GD.txt)

**Comment by laurenceanthony** [comment]
Lovely example. Really nice. I assume you know that it's been used by Siraj Raval as part of his new YouTube series.

**Comment by vladtyum** [comment]
Hi Matt! @mattnedrich 
thanks so much for your article and example, it really helped to understand very basic machinery inside all this "magical" machine learning.
One more thing:  could you please put your visualisation code on github. I want to make the same but with 3d plot for 2 variables. Having your simple and beautiful visualisation code would be helpful to take as an example.
Thanks in advance ;)  
Vlad.

**Comment by anandpawara** [comment]
Hi Matt.
I tried running your code but i am getting error


$ python gradient_descent_example.py
  File "gradient_descent_example.py", line 39
    print "Starting gradient descent at b = {0}, m = {1}, error = {2}".format(in   itial_b, initial_m, compute_error_for_line_given_points(initial_b, initial_m, po   ints))
                                                                     ^
SyntaxError: invalid syntax

pls help

**Comment by AppsusUK** [comment]
@anandpawara you are getting this error because the file is written for python 2, you probably have python 3 installed. The issue is print is a function thus needs to be wrapped in () in python 3.
So if you add ( ) around lines you want to print, it will fix the issue when running.

`    print ("Starting gradient descent at b = {0}, m = {1}, error = {2}".format(initial_b, initial_m, compute_error_for_line_given_points(initial_b, initial_m, points)))`

`    print ("Running...")`

`    print ("After {0} iterations b = {1}, m = {2}, error = {3}".format(num_iterations, b, m, compute_error_for_line_given_points(b, m, points)))`
