### ISSUE TITLE
Running the file gives an error 

### ISSUE THREAD

**Issue by vijayksingh** [mattnedrich/GradientDescentExample#4]
![capture](https://cloud.githubusercontent.com/assets/11094580/22089032/7b117704-de0e-11e6-9fb3-c5658cd91416.PNG)

Running the file gives this error. I am a beginner can't get around this. Please help !

**Comment by mattnedrich** [comment]
My guess is that you are using a version of Python older than 2.6 - http://stackoverflow.com/questions/792721/string-formatting-in-python-version-earlier-than-2-6

**Comment by Jekus** [comment]
Remove the parenthesis before 'format' and add another parenthesis at the end of the whole 'print'.

```python
print("Starting gradient descent at b = {}, m = {}, error = {}".format(initial_b, initial_m, compute_error_for_line_given_points(initial_b, initial_m, points)))
```

**Comment by mattnedrich** [comment]
I recommend you update your Python version to 2.6 or newer. I will note this version requirement in the README.
